# Generated by Django 3.1.4 on 2021-01-01 04:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201229_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
