# Generated by Django 3.1.4 on 2021-01-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210106_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='shipping_address',
        ),
    ]
