# Generated by Django 3.1.4 on 2021-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210106_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_options',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'Paypal')], max_length=2, null=True),
        ),
    ]
