# Generated by Django 3.1.4 on 2021-01-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shippingaddress_payment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='payment_options',
            new_name='payment_option',
        ),
    ]
