# Generated by Django 3.1.4 on 2021-01-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210108_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='billing_address',
        ),
    ]
