# Generated by Django 3.1.4 on 2021-01-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210123_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
