# Generated by Django 3.1.4 on 2021-02-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20210216_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer',
            field=models.ManyToManyField(blank=True, to='shop.Customer'),
        ),
    ]
