# Generated by Django 3.1.4 on 2021-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20210217_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='shop.Coupon'),
        ),
    ]
