# Generated by Django 3.1.4 on 2021-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20210217_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, related_name='user_coupons', to='shop.Coupon'),
        ),
    ]
