# Generated by Django 3.1.4 on 2021-02-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20210217_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
