# Generated by Django 3.1.4 on 2021-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20210217_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='shop.Coupon'),
        ),
    ]
